### ISSUE TITLE
Why not request.fullpath?

### ISSUE THREAD

**Issue by nanaya** [turbolinks/turbolinks-rails#13]
From what I can tell, xhr request still includes the `Turbolinks-Referrer` header even when redirecting, so instead of storing redirect url in session, isn't it simpler to just use `request.fullpath` when setting the header? Is there specific reason to not do it?

``` ruby
# lib/turbolinks/redirection.rb#L43
if request.headers["Turbolinks-Referrer"].present?
  response.headers["Turbolinks-Location"] = request.fullpath
end
```

(unfortunately I don't have testable app - I'm realizing this when using turbolinks from non-ruby app and reimplementing the integration)

**Comment by packagethief** [comment]
I think the reason was to avoid setting `Turbolinks-Location` when redirection hasn't occurred. I think it's conceptually simpler if we always set it, though, which would remove our dependency on the session. [Turbolinks.Visit.followRedirect](https://github.com/turbolinks/turbolinks/blob/676c5ba/src/turbolinks/visit.coffee#L79-L83) could then check to see whether the location differs from the current location and only replace history if it does.

**Comment by nanaya** [comment]
Ah, I see now. Thank you.
